import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { FaMoon } from "react-icons/fa";
import { FaGithub } from "react-icons/fa6";
import { FaLinkedin } from "react-icons/fa6";
import { FaSquareTwitter } from "react-icons/fa6";
import { IoMdMail } from "react-icons/io";
import { IoLogoWhatsapp } from "react-icons/io";
//framer
import {motion} from "framer-motion";

{/*image import*/}
import profileImage from "../public/P1.png"
import Java from "../public/Java.png"
import code from "../public/c.png"
import react from "../public/1.png"
import tailwind from "../public/2.png"
import php from "../public/6.png"
import js from "../public/7.png"
import html from "../public/3.png"
import css from "../public/4.png"
import boot from "../public/5.png"

import img1 from "../public/project01.png"
import img2 from "../public/project02.png"
import img3 from "../public/project03.png"
import img4 from "../public/project04.png"
import img5 from "../public/project05.png"
import img6 from "../public/ps.png"
import img7 from "../public/xd.png"
import img8 from "../public/canva.png"
import img9 from "../public/figma.png"
import { useState } from "react";

//popup
import Modal from 'react-modal';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  //function dark
  const [darkMode, setDarkMode] = useState(false);

  const [modalIsOpen, setModalIsOpen] = useState(false);
  const [modalContent, setModalContent] = useState("");

  const openModal = (content) => {
    setModalContent(content);
    setModalIsOpen(true);
  };
  const closeModal = () => {
    setModalIsOpen(false);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hasitha Dilshan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myphoto.png" />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700;800&display=swap');
        </style>

      </Head>
      <main className="font-Poppins bg-yellow-50 min-h-screen px-10 md:px-20 lg:px-40 dark:bg-black">
        <section>

          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-xl dark:text-white">My Portfolio</h1>
              <ul className=" flex items-center">
                <li>
                  <FaMoon onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-xl mx-5 dark:text-white" />
                </li>

                <li>
                  <a href="https://drive.google.com/file/d/1ookigFh1bF4dQutsBMDwAro6d8UtH3d4/view?usp=sharing" 
                  download={"resume"}
                  className=" bg-yellow-400 text-black px-4 py-2 border-none rounded-md">Resume</a>
                </li>

              </ul>
          </nav>

          {/*hero section*/}
          <div className=" text-center p-10">
            <h1 className=" text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-4">Hasitha Dilshan</h1>
            <h3 className=" text-2xl py-4 md:text-3xl dark:text-white">SOFTWARE ENGINEERING UNDERGRADUATE</h3>
            <p className="text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto md:text-lg dark:text-white">
              I am Hasitha, currently completing an HND in Computing at IDM Nations Campus. With expertise in Web Design, UI/UX, and Frontend Development, I have built a strong foundation in creating engaging and user-friendly interfaces. I am committed to continuous learning and eager to contribute my skills to innovative and sustainable projects.
            </p>
          </div>

          {/*socials*/}
          <div className=" text-5xl flex justify-center gap-16 text-gray-600">

            <a href="https://github.com/HasithaDi">
            <FaGithub />
            </a>

            <a href="http://linkedin.com/in/hasitha-dilshan-a0a7802b2">
              <FaLinkedin />
            </a>

            <a href="https://x.com/@HaSiD2531">
              <FaSquareTwitter />
            </a>

          </div>

          {/*profile*/}
          <motion.div initial = {{opacity:0, scale:0.5}} animate={{opacity:1, scale:1}} transition={{duration:0.5}}>
            <div className=" m-auto relative bg-gradient-to-b from-slate-600 w-96 h-96 p-5 mt-20 rounded-full">
            <Image src={profileImage} alt="Profile Image" layout="fill" objectFit="cover" className="rounded-full"/>
            </div>
          </motion.div>

        </section>

        {/*skills*/}
        <section>
          <div>
            <h2 className=" text-5xl py-10 font-bold dark:text-white">MY SKILLS</h2>
            <h3 className=" text-2xl py-10 font-bold opacity-60 dark:text-white">PROGRAMMING LANGUAGE</h3>
          </div>

          {/*skill programming language*/}
          <div className="flex justify-center items-center">
          <div className=" md:flex lg:flex gap-10 mx-auto">
            {/*card*/}
            <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
            <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 dark:bg-white">
              <Image src={Java} alt="Java language" width={100} height={100} className=" inline"/>
              <h2 className=" text-2xl font-bold">Java</h2>
            </div>
            </motion.div>

            {/*card*/}
            <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
            <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 dark:bg-white">
              <Image src={code} alt="C# language" width={100} height={100} className=" inline"/>
              <h2 className=" text-2xl font-bold">C#</h2>
            </div>
            </motion.div>
          </div>
          </div>

          {/*skill web development*/}
          <div>
            <h3 className=" text-2xl py-10 font-bold opacity-60 dark:text-white">WEB DEVELOPMENT</h3>
          </div>

          <div className="flex justify-center items-center">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 mx-auto">
              {/*card*/}
              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={react} alt="React language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">React</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={tailwind} alt="Tailwind CSS" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Tailwind CSS</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={php} alt="PHP language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">PHP</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className="border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={js} alt="JavaScript language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">JavaScript</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className="border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={boot} alt="Bootstrap language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Bootstrap</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className="border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={html} alt="HTML language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">HTML</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className="border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={css} alt="CSS language" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">CSS</h2>
                </div>
              </motion.div>
            </div>
           </div>

        </section>

        {/*project*/}
        
        <section>
          <div>
            <h2 className=" text-5xl py-10 font-bold opacity-60 dark:text-white">PROJECT</h2>
          </div>

          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
            <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
              <Modal
                isOpen={modalIsOpen}
                onRequestClose={closeModal}
                contentLabel="Image Details"
                className="bg-white p-5 rounded-lg shadow-lg max-w-xl mx-auto"
                overlayClassName="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center"
              >
                {modalContent} {/* Updated to use modalContent state variable */}
                <button onClick={closeModal} className="mt-4 bg-blue-500 text-white px-4 py-2 rounded-md">
                  Close
                </button>
              </Modal>

              {/*Winton hospital*/}
              <div className="basis-1/3 flex-1">
                <motion.div
                  whileHover={{ scale: 1.1, rotate: 3 }}
                  whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
                  onClick={() => openModal(
                    <div>
                      <h2 className="text-xl font-bold mb-4">Project Details</h2>
                      <p>A website that can facilitate the operation of a hospital. Here you can add, update and delete patient details, doctor details, nurse details.</p>
                      <ul className="list-disc list-inside mt-2">
                        <li>The front end of the web page was created using HTML, CSS, JS and Bootstrap.</li>
                        <li>Image edited using Canva and Figma.</li>
                        <li>The back end is completed using PHP.</li>
                        <li>The database was prepared using MySql.</li>
                        <li>Added SublimeText as editor.</li>
                      </ul>
                    </div>
                  )}
                >
                <Image src={img1} alt="Winton hospital" layout="responsive" className="rounded-lg object-cover" />
                </motion.div>
          </div>

          {/*New lanka hospital*/}

          <div className="basis-1/3 flex-1">
            <motion.div
              whileHover={{ scale: 1.1, rotate: 3 }}
              whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              onClick={() => openModal(
                <div>
                  <h2 className="text-xl font-bold mb-4">Project Details</h2>
                  <p>The interface consists of a sidebar menu for a healthcare management system with options for managing patients, medications, doctors, nurses, providers, invoices, admin tasks and logouts. Each option is represented by an illustrative icon for easy navigation and quick access to various functions within the system. Insertions, updates and deletions can be performed.</p>
                  <ul className="list-disc list-inside mt-2">
                    <li>This application was created using Java.</li>
                    <li>Image edited using Canva and Photoshop.</li>
                    <li>The database was prepared using MySql (XAMPP).</li>
                    <li>Added Apache NetBeans IDE 18 as the editor.</li>
                  </ul>
                </div>
              )}
            >
            <Image src={img2} alt="New lanka hospital" layout="responsive" className="rounded-lg object-cover" />
            </motion.div>
          </div>

          {/*Pro health hospital*/}

          <div className="basis-1/3 flex-1">
            <motion.div
              whileHover={{ scale: 1.1, rotate: 3 }}
              whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              onClick={() => openModal(
                <div>
                  <h2 className="text-xl font-bold mb-4">Project Details</h2>
                  <p>A desktop application that can facilitate the operation of a hospital.Here you can enter patients, details of doctors, details of nurses, delete, updates and search.</p>
                  <ul className="list-disc list-inside mt-2">
                    <li>This application was created using Java.</li>
                    <li>Image edited using Canva and Photoshop.</li>
                    <li>The database was prepared using MySql.</li>
                    <li>Added Apache NetBeans IDE 18 as the editor.</li>
                  </ul>
                </div>
              )}
            >
              <Image src={img3} alt="Pro health hospital" layout="responsive" className="rounded-lg object-cover" />
            </motion.div>
          </div>

          {/*Ship booking system*/}

          <div className="basis-1/3 flex-1">
            <motion.div
              whileHover={{ scale: 1.1, rotate: 3 }}
              whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              onClick={() => openModal(
                <div>
                  <h2 className="text-xl font-bold mb-4">Project Details</h2>
                  <p>The Oceanlink Express interface features a sidebar menu for easy navigation, offering options such as Home, Booking, Ports, Company, Ships, Admin and Checkout. The booking section allows users to enter passenger details, select ships and class and manage seat bookings including calculating totals, discounts and net amounts. The system provides options to add or remove passengers, save and print booking details and clarify entries. The top bar shows the current date and time, along with a welcome message for the administrator. You can make entries, updates, deletes, searches and print a bill.</p>
                  <ul className="list-disc list-inside mt-2">
                    <li>This application was created using C#.</li>
                    <li>Image edited using Canva.</li>
                    <li>The database was prepared using MySql (XAMPP).</li>
                    <li>Added Visual Studio Code as the editor.</li>
                  </ul>
                </div>
              )}
            >
              <Image src={img4} alt="Ship booking system" layout="responsive" className="rounded-lg object-cover" />
            </motion.div>
          </div>

          {/*Mobile application*/}

          <div className="basis-1/3 flex-1">
            <motion.div
              whileHover={{ scale: 1.1, rotate: 3 }}
              whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              onClick={() => openModal(
                <div>
                  <h2 className="text-xl font-bold mb-4">Project Details</h2>
                  <p>The project's main objective is to create a user-friendly eBook application that offers effortless access to a wide range of free books and audiobooks.</p>
                  <ul className="list-disc list-inside mt-2">
                    <li>Image edited using canva and photoshop.</li>
                    <li>UI design tool is figma.</li>
                  </ul>
                </div>
              )}
            >
              <Image src={img5} alt="Mobile application" layout="responsive" className="rounded-lg object-cover" />
            </motion.div>
          </div>
        </div>

          </div>
        </section>

        {/*Tools*/}

        <section>
          <div>
            <h2 className=" text-5xl py-10 font-bold dark:text-white">TOOLS</h2>
            <h3 className=" text-2xl py-10 font-bold opacity-60 dark:text-white">DESIGNING TOOLS</h3>
          </div>

          {/*designing tools*/}
          <div className="flex justify-center items-center">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 mx-auto">
              {/*card*/}
              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={img9} alt="Figma" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Figma</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={img7} alt="Adobe XD" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Adobe XD</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className=" border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={img6} alt="Photoshop" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Photoshop</h2>
                </div>
              </motion.div>

              <motion.div whileHover={{scale:1.1}} whileTap={{scale:0.9}}>
                <div className="border-l-gray-600 text-center shadow-sm p-5 rounded-xl m-10 w-56 h-45 dark:bg-white">
                  <Image src={img8} alt="Canva" width={100} height={100} className="inline"/>
                  <h2 className="text-2xl font-bold">Whsaaa</h2>
                </div>
              </motion.div>
            </div>
           </div>
          </section> 

        {/*footer*/}
        <footer className=" border-t-2 border-black text-sm opacity-70 flex-col gap-5 items-center justify-center py-10 lg:flex-row lg:items-center dark:text-white dark:border-white">
          <div>
            <h3 className=" text-base mb-2">contact me for more details</h3>
          </div>
          <div>
            <div className=" text-5xl flex justify-center gap-16 text-gray-600">

            <a href="https://github.com/HasithaDi">
            <FaGithub />
            </a>

            <a href="http://linkedin.com/in/hasitha-dilshan-a0a7802b2">
              <FaLinkedin />
            </a>

            <a href="https://x.com/@HaSiD2531">
              <FaSquareTwitter />
            </a>

            <a href="dilshanhasitha254@gmail.com">
              <IoMdMail />
            </a>

            <a href="https://+94760735551">
              <IoLogoWhatsapp />
            </a>

          </div>
          </div>

        </footer>

      </main>
    </div>
  );
}
